### ISSUE TITLE
Is Chackra Runtime is some mini-browser?

### ISSUE THREAD

**Issue by mediaexplorer74** [527395632/ChakraRuntime#1]
Hi, [527395632](https://github.com/527395632)! 
Is Chackra Runtime is some mini-browser?
My dream is to build some good browser for obsolete windows-phone Lumia 950 
Best,
[m][e]

**Comment by 527395632** [comment]
No, this is just a simple JavaScript runtime. If you need to be a browser, you can consider Google Chrome

**Comment by mediaexplorer74** [comment]
[527395632](https://github.com/527395632), thank you for reply. 
Ohhh... I have no resources to compile (build) CEF from sources... And CEF does not support Windows ARM32.... only 64 :(

**Comment by mediaexplorer74** [comment]
simple JavaScript runtime ? Wow... I see :) 3 years ago I tried to use Chackra Core :) This is some JS-to-C# "connector"... idk how to really use it in my life ))
Ok... please close my "issue". Sorry if disturb you

**Comment by 527395632** [comment]
https://cef-builds.spotifycdn.com/index.html
https://gitlab.com/xiliumhq/chromiumembedded/cefglue/

Yes, you can see the link above
